import { AfterViewInit, EventEmitter, OnInit } from '@angular/core';
import * as i0 from "@angular/core";
export declare class NgxFormChatComponent implements OnInit, AfterViewInit {
    openChat: any;
    config: any;
    data: any;
    useSession: boolean;
    restartChatWhenOpen: boolean;
    onEndChat: EventEmitter<any>;
    defaultConfig: any;
    chatbotData: any;
    title: string;
    startDate: string;
    pushMessageTimer: any;
    isTyping: Boolean;
    endChat: Boolean;
    currentIndex: number;
    isEcrit: Boolean;
    initialWidth: string;
    initialHeight: string;
    chatlist: any;
    returnJSON: any;
    inputValue: string;
    constructor();
    ngOnInit(): void;
    startChat(): void;
    initChatConfig(): void;
    pushChat(user: string): void;
    saveState(inputValue: string): void;
    getState(): void;
    pushMessage(messages: string, index: number): void;
    fitVariables(message: string, chat: any): string;
    getAnswer(inputValue: string): void;
    sendError(inputValue: string): void;
    pushChatError(user: string): void;
    handleValidation(inputValue: string): boolean;
    continueChat(inputValue: string): void;
    handleSuivant(inputValue: string): any;
    handleFin(): void;
    handleOpenChat(): void;
    restartChat(): void;
    ngAfterViewInit(): void;
    handleSize(width: number, height: number): void;
    scrollToLastMessage(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxFormChatComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxFormChatComponent, "ngx-form-chat", never, { "openChat": "openChat"; "config": "config"; "data": "data"; "useSession": "useSession"; "restartChatWhenOpen": "restartChatWhenOpen"; }, { "onEndChat": "onEndChat"; }, never, never>;
}
